"""Añadir columna usuario a imagen

Revision ID: faf6dd2a1807
Revises: 89800882d599
Create Date: 2025-05-06 17:16:39.751125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf6dd2a1807'
down_revision = '89800882d599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
